/// Seal access policy: the decryption key for a SealedEval is released ONLY to
/// the registered, attested enclave. Seal key servers evaluate `seal_approve`
/// (in a dry-run) before returning key shares; it aborts unless the caller
/// presents an ed25519 signature by the enclave's key over the access intent.
module sealedbench::seal_policy {
    use enclave::enclave::{Self, Enclave};

    const EInvalidEnclave: u64 = 1;
    /// Intent scope byte for Seal access (distinct from score attestation = 1).
    const SEAL_INTENT: u8 = 2;

    /// The exact message the enclave signs to request a key. Field order MUST
    /// match the Rust enclave's BCS serialization.
    public struct SealApproval has copy, drop {
        id: vector<u8>,
    }

    /// `id` is the IBE identity Seal is asked to release a key for. Aborts unless
    /// `signature` is a valid enclave-key signature over
    /// IntentMessage{SEAL_INTENT, timestamp_ms, SealApproval{id}}.
    entry fun seal_approve<T>(
        id: vector<u8>,
        enclave: &Enclave<T>,
        timestamp_ms: u64,
        signature: vector<u8>,
    ) {
        assert!(
            enclave::verify_signature(
                enclave,
                SEAL_INTENT,
                timestamp_ms,
                SealApproval { id },
                &signature,
            ),
            EInvalidEnclave,
        );
    }

    // Test vectors generated by tools/gen-attestation-vectors.ts (fixed seed).
    #[test_only]
    public struct TESTW has drop {}
    #[test_only]
    const PK: vector<u8> = x"79b5562e8fe654f94078b112e8a98ba7901f853ae695bed7e0e3910bad049664";
    #[test_only]
    const SEAL_SIG: vector<u8> =
        x"9513b9fe9d920e6ec473b9245d2776d7af972c305e29d319056d69c2faa1456829d2b0df3cb4ba83311e289703bb57a08d0cc378e85a78f5b9d6e4f71a269409";
    #[test_only]
    const TS: u64 = 1744038900000;

    #[test]
    fun seal_approve_accepts_enclave_signature() {
        let mut scenario = sui::test_scenario::begin(@0xA11CE);
        let e = enclave::new_enclave_for_testing<TESTW>(
            PK,
            sui::test_scenario::ctx(&mut scenario),
        );
        seal_approve(x"22222222222222222222222222222222", &e, TS, SEAL_SIG);
        enclave::destroy(e);
        sui::test_scenario::end(scenario);
    }

    #[test]
    #[expected_failure(abort_code = EInvalidEnclave)]
    fun seal_approve_rejects_wrong_identity() {
        let mut scenario = sui::test_scenario::begin(@0xA11CE);
        let e = enclave::new_enclave_for_testing<TESTW>(
            PK,
            sui::test_scenario::ctx(&mut scenario),
        );
        // Different id than what was signed -> signature fails to verify.
        seal_approve(x"33333333333333333333333333333333", &e, TS, SEAL_SIG);
        enclave::destroy(e);
        sui::test_scenario::end(scenario);
    }
}
